services:
  app:
    build: .
    container_name: captive-portal-app
    env_file:
      - .env
    environment:
      TZ: America/Sao_Paulo
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: portal
      DB_PASSWORD: portal123
      DB_NAME: captive_portal
      TERMS_VERSION: v1.0
      PRIVACY_VERSION: v1.0
      NBI_REQUEST_USERNAME: external-portal
      NBI_REQUEST_PASSWORD: changeme
      SZ_MANAGEMENT_IP: 10.0.0.10
      NBI_MOCK: "true"
      NBI_TLS_INSECURE: "true"
    volumes:
      - ./logs:/app/logs
    depends_on:
      - postgres

  nginx:
    image: nginx:1.27-alpine
    container_name: captive-portal-nginx
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  postgres:
    image: postgres:16-alpine
    container_name: captive-portal-db
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_DB: captive_portal
      POSTGRES_USER: portal
      POSTGRES_PASSWORD: portal123
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/postgres/initdb:/docker-entrypoint-initdb.d:ro

  freeradius:
    image: freeradius/freeradius-server:latest
    container_name: captive-portal-radius
    depends_on:
      - postgres
    volumes:
      - ./freeradius/clients.conf:/etc/freeradius/3.0/clients.conf:ro
      - ./freeradius/mods-enabled/sql:/etc/freeradius/3.0/mods-enabled/sql:ro
      - ./freeradius/sql/main/postgresql/queries.conf:/etc/freeradius/3.0/mods-config/sql/main/postgresql/queries.conf:ro
    environment:
      DB_SERVER: postgres
      DB_PORT: 5432
      DB_LOGIN: portal
      DB_PASSWORD: portal123
      DB_NAME: captive_portal
    ports:
      - "1812:1812/udp"
      - "1813:1813/udp"

volumes:
  pgdata:
