authorize_check_query = "SELECT id, username_radius AS UserName, password_hash AS Password FROM users WHERE username_radius = '%{SQL-User-Name}' AND is_active = true"
authorize_reply_query = "SELECT id, username_radius AS UserName FROM users WHERE username_radius = '%{SQL-User-Name}' AND is_active = true"
