CREATE TABLE IF NOT EXISTS users (
  id BIGSERIAL PRIMARY KEY,
  cpf VARCHAR(11) UNIQUE NOT NULL,
  phone VARCHAR(20) NOT NULL,
  username_radius VARCHAR(64) UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMPTZ NOT NULL DEFAULT NOW() + INTERVAL '30 days',
  is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS lgpd_consents (
  id BIGSERIAL PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  accepted_terms BOOLEAN NOT NULL,
  accepted_privacy BOOLEAN NOT NULL,
  accepted_processing BOOLEAN NOT NULL,
  terms_version VARCHAR(50) NOT NULL,
  privacy_version VARCHAR(50) NOT NULL,
  accepted_at TIMESTAMPTZ NOT NULL,
  ip VARCHAR(64),
  user_agent TEXT
);
