ALTER TABLE login_sessions
  ALTER COLUMN user_id DROP NOT NULL,
  ADD COLUMN IF NOT EXISTS nbi_ip VARCHAR(64),
  ADD COLUMN IF NOT EXISTS uip VARCHAR(64),
  ADD COLUMN IF NOT EXISTS client_mac VARCHAR(32),
  ADD COLUMN IF NOT EXISTS proxy VARCHAR(32),
  ADD COLUMN IF NOT EXISTS ssid VARCHAR(128),
  ADD COLUMN IF NOT EXISTS sip VARCHAR(64),
  ADD COLUMN IF NOT EXISTS dn VARCHAR(255),
  ADD COLUMN IF NOT EXISTS wlan_name VARCHAR(128),
  ADD COLUMN IF NOT EXISTS url TEXT,
  ADD COLUMN IF NOT EXISTS apip VARCHAR(64),
  ADD COLUMN IF NOT EXISTS vlan VARCHAR(64),
  ADD COLUMN IF NOT EXISTS authorized_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS stage VARCHAR(32),
  ADD COLUMN IF NOT EXISTS radius_username VARCHAR(64),
  ADD COLUMN IF NOT EXISTS login_password TEXT;

ALTER TABLE otp_codes
  ADD COLUMN IF NOT EXISTS login_session_id VARCHAR(64);

CREATE INDEX IF NOT EXISTS idx_login_sessions_expires_at ON login_sessions (expires_at);
CREATE INDEX IF NOT EXISTS idx_otp_codes_login_session_created ON otp_codes (login_session_id, created_at DESC);
